name: moments
description: A Flutter event management app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  curved_navigation_bar: ^1.0.6
  emoji_picker_flutter: ^4.3.0
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.3.0
  http: ^1.4.0
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  marquee: ^2.3.0
  mime: ^2.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  flutter_cache_manager: ^3.4.1
  dio: ^5.9.0
  device_info_plus: ^12.0.0
  country_code_picker: ^3.4.0
  flutter_contacts: ^1.1.9+2
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
